# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 99ddf8aae3fed31fe72fbcb4a748524d5b5639201f4ad05940bf03f08fce54d5f89419c87ec91225139dadc17bfee3b8ed6698f44910d16cd8cb239754110228

test:
  secret_key_base: 7a9ca1f61ce1f46460423ace5a873c08de105940933d5e506f3904b4ffdfc9a5256ca64f3479a095fd5fa541a4e7230c79f682fe0022a80cd26419abacf95cb3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
