require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe GrmailsController do

  # This should return the minimal set of attributes required to create a valid
  # Grmail. As you add validations to Grmail, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "email" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # GrmailsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all grmails as @grmails" do
      grmail = Grmail.create! valid_attributes
      get :index, {}, valid_session
      assigns(:grmails).should eq([grmail])
    end
  end

  describe "GET show" do
    it "assigns the requested grmail as @grmail" do
      grmail = Grmail.create! valid_attributes
      get :show, {:id => grmail.to_param}, valid_session
      assigns(:grmail).should eq(grmail)
    end
  end

  describe "GET new" do
    it "assigns a new grmail as @grmail" do
      get :new, {}, valid_session
      assigns(:grmail).should be_a_new(Grmail)
    end
  end

  describe "GET edit" do
    it "assigns the requested grmail as @grmail" do
      grmail = Grmail.create! valid_attributes
      get :edit, {:id => grmail.to_param}, valid_session
      assigns(:grmail).should eq(grmail)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Grmail" do
        expect {
          post :create, {:grmail => valid_attributes}, valid_session
        }.to change(Grmail, :count).by(1)
      end

      it "assigns a newly created grmail as @grmail" do
        post :create, {:grmail => valid_attributes}, valid_session
        assigns(:grmail).should be_a(Grmail)
        assigns(:grmail).should be_persisted
      end

      it "redirects to the created grmail" do
        post :create, {:grmail => valid_attributes}, valid_session
        response.should redirect_to(Grmail.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved grmail as @grmail" do
        # Trigger the behavior that occurs when invalid params are submitted
        Grmail.any_instance.stub(:save).and_return(false)
        post :create, {:grmail => { "email" => "invalid value" }}, valid_session
        assigns(:grmail).should be_a_new(Grmail)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Grmail.any_instance.stub(:save).and_return(false)
        post :create, {:grmail => { "email" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested grmail" do
        grmail = Grmail.create! valid_attributes
        # Assuming there are no other grmails in the database, this
        # specifies that the Grmail created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Grmail.any_instance.should_receive(:update).with({ "email" => "MyString" })
        put :update, {:id => grmail.to_param, :grmail => { "email" => "MyString" }}, valid_session
      end

      it "assigns the requested grmail as @grmail" do
        grmail = Grmail.create! valid_attributes
        put :update, {:id => grmail.to_param, :grmail => valid_attributes}, valid_session
        assigns(:grmail).should eq(grmail)
      end

      it "redirects to the grmail" do
        grmail = Grmail.create! valid_attributes
        put :update, {:id => grmail.to_param, :grmail => valid_attributes}, valid_session
        response.should redirect_to(grmail)
      end
    end

    describe "with invalid params" do
      it "assigns the grmail as @grmail" do
        grmail = Grmail.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Grmail.any_instance.stub(:save).and_return(false)
        put :update, {:id => grmail.to_param, :grmail => { "email" => "invalid value" }}, valid_session
        assigns(:grmail).should eq(grmail)
      end

      it "re-renders the 'edit' template" do
        grmail = Grmail.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Grmail.any_instance.stub(:save).and_return(false)
        put :update, {:id => grmail.to_param, :grmail => { "email" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested grmail" do
      grmail = Grmail.create! valid_attributes
      expect {
        delete :destroy, {:id => grmail.to_param}, valid_session
      }.to change(Grmail, :count).by(-1)
    end

    it "redirects to the grmails list" do
      grmail = Grmail.create! valid_attributes
      delete :destroy, {:id => grmail.to_param}, valid_session
      response.should redirect_to(grmails_url)
    end
  end

end
